apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
  namespace: canary
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollouts-demo
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: 
            duration: 100s
        - setWeight: 40
        - pause:
            duration: 100s
        - setWeight: 60
        - pause: {}
        - setWeight: 80
        - pause:
            duration: 100s
        - setWeight: 100
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
        - name: rollouts-demo
          image: argoproj/rollouts-demo:red
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "40m"
              memory: "64Mi"
            requests:
              cpu: "20m"
              memory: "32Mi"
